version: '3'

services:
  fluent-bit:
    image: fluent/fluent-bit:2.1.10
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ./../storage/logs/audit.log:/var/logs/audit.log
    environment:
      - LOKI_ENV=erp-qa
