name: Code Standards Check

on:
  pull_request:
    paths:
      - 'app/**'
      - 'config/**'
      - 'database/**'
      - 'public/**'
      - 'resources/**'
      - 'routes/**'
      # Add more paths as needed

jobs:
  code_standards:
    runs-on: arc-runner-set

    steps:

      - name: Install Git
        run: sudo apt update && sudo apt-get -y install git
        
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clone
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: '7.3'
          extensions: mbstring,PDO,xml,json,openssl,bcmath,gd

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHP_CodeSniffer on changed files
        run: ./vendor/bin/phpcs --standard=PSR2 --extensions=php ${{ steps.changed-files.outputs.all_changed_files }}
